name: flutter_emoji
description: "👉 A light-weight Emoji 📦 for Flutter with all up-to-date emojis 😄. Made from 💯% ☕ with ❤️!"
version: 2.4.0
homepage: "https://github.com/petehouston/flutter-emoji"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.2.0
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  lint: ^1.0.0
  test: ^1.20.1